import { test, expect, type Page } from '@playwright/test';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { createServer } from 'node:http';
import path from 'node:path';

const evidence=path.resolve('test-results/film-evidence');
const getProject=(page:Page)=>page.evaluate(()=>(window as any).__film.getProject());
const state=(page:Page)=>page.evaluate(()=>(window as any).__film.state());
const history=(page:Page)=>page.evaluate(()=>(window as any).__film.history());
async function settle(page:Page){await page.evaluate(()=>new Promise<void>(r=>requestAnimationFrame(()=>requestAnimationFrame(()=>r()))));}
async function ready(page:Page){await page.goto('./');await expect(page.locator('html')).toHaveAttribute('data-ready','true');await page.locator('#film-start').click();await settle(page);}
async function change(page:Page,label:string,value:string){await page.getByRole('spinbutton',{name:label,exact:true}).fill(value);await page.getByRole('spinbutton',{name:label,exact:true}).press('Tab');await settle(page);}
async function shot(page:Page,file:string){await settle(page);await page.screenshot({path:path.join(evidence,file)});}
async function pixels(page:Page,selector:string){return page.locator(selector).evaluate(el=>{const c=document.createElement('canvas');c.width=160;c.height=90;const ctx=c.getContext('2d')!;ctx.drawImage(el as HTMLCanvasElement,0,0,160,90);return [...ctx.getImageData(0,0,160,90).data];});}
function difference(a:number[],b:number[]){let sum=0;for(let i=0;i<a.length;i++)if(i%4!==3)sum+=Math.abs(a[i]-b[i]);return sum/(a.length*.75);}
test.beforeAll(async()=>{await mkdir(evidence,{recursive:true});});
test.beforeEach(async({page})=>{page.on('dialog',d=>d.accept());});

test('短片完整验收：修改第二镜头、播放、保存刷新、真实视频下载并打开检查',async({page,browser})=>{
  test.setTimeout(process.env.CI?480000:240000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await ready(page);
  let p=await getProject(page);expect(p.version).toBe(2);expect(p.film.shots).toHaveLength(3);expect(p.film.shots.reduce((n:number,s:any)=>n+s.duration,0)).toBe(10);
  await shot(page,'01-film-default-1440x900.png');
  const roomLink=await page.locator('#edit-room').boundingBox(),pane=await page.locator('.shot-panel').boundingBox();expect(roomLink!.y+roomLink!.height).toBeLessThanOrEqual(pane!.y+pane!.height);
  await page.locator('#shot-list [data-shot="shot-2"]').click();await page.locator('[data-endpoint="end"]').click();await change(page,'景别缩放','1.83');await change(page,'水平角','44');await change(page,'观察目标 X','0.55');await change(page,'镜头时长','3.8');
  expect((await getProject(page)).selectedShotId).toBe('shot-2');expect((await getProject(page)).film.shots[1].end.zoom).toBe(1.83);
  await page.getByRole('textbox',{name:'镜头名称',exact:true}).fill('桌边 · 我的灵感');await page.getByRole('textbox',{name:'镜头名称',exact:true}).press('Tab');
  await page.getByRole('button',{name:'播放短片',exact:true}).click();await page.waitForTimeout(500);expect((await state(page)).playing).toBe(true);await page.getByRole('button',{name:'暂停短片',exact:true}).click();const paused=(await getProject(page)).playhead;await page.waitForTimeout(180);expect((await getProject(page)).playhead).toBe(paused);
  await page.locator('#shot-list [data-shot="shot-2"]').click();await page.locator('[data-endpoint="end"]').click();await page.setViewportSize({width:1280,height:800});await shot(page,'02-film-second-1280x800.png');
  const propertyBottom=await page.locator('#shot-delete').boundingBox(),timeline=await page.locator('.film-timeline').boundingBox();expect(propertyBottom!.y+propertyBottom!.height).toBeLessThanOrEqual(timeline!.y+1);
  const roomLinkSmall=await page.locator('#edit-room').boundingBox();expect(roomLinkSmall!.y+roomLinkSmall!.height).toBeLessThanOrEqual(timeline!.y);
  await page.getByRole('textbox',{name:'工程名称',exact:true}).fill('光落书房 · 镜头验收');await page.getByRole('textbox',{name:'工程名称',exact:true}).press('Tab');
  await page.getByRole('button',{name:'保存工程',exact:true}).click();await expect(page.locator('#film-save-state')).toHaveText('已保存到本地');const saved=await getProject(page);
  await page.reload();await expect(page.locator('html')).toHaveAttribute('data-ready','true');expect(await getProject(page)).toEqual(saved);expect((await state(page)).playing).toBe(false);
  const jsonDownload=page.waitForEvent('download');await page.locator('#film-json').click();const json=await jsonDownload;const jsonPath=path.join(evidence,'verified-film-project.json');await json.saveAs(jsonPath);expect(JSON.parse(await readFile(jsonPath,'utf8'))).toEqual(saved);
  await change(page,'水平角','60');await page.locator('#film-file').setInputFiles(jsonPath);expect(await getProject(page)).toEqual(saved);
  await page.waitForFunction(()=>(window as any).__film.state().encoderReady);expect((await state(page)).formats.length).toBeGreaterThan(0);
  await page.getByRole('button',{name:'导出视频',exact:true}).click();const format=await page.locator('#film-codec').inputValue();await page.getByRole('button',{name:'生成视频',exact:true}).click();
  await expect(page.locator('#video-result')).toBeVisible({timeout:process.env.CI?360000:160000});await expect(page.locator('#export-error')).toHaveText('');await page.waitForFunction(()=>document.querySelector<HTMLVideoElement>('#film-video')!.readyState>=3);await shot(page,'03-film-export-and-replay.png');
  const videoInfo=await page.locator('#film-video').evaluate((el:HTMLVideoElement)=>({duration:el.duration,width:el.videoWidth,height:el.videoHeight,ready:el.readyState}));expect(videoInfo.duration).toBeCloseTo(10.2,1);expect([videoInfo.width,videoInfo.height]).toEqual([1280,720]);
  const downloadEvent=page.waitForEvent('download');await page.getByRole('button',{name:'下载视频',exact:true}).click();const downloaded=await downloadEvent;const videoPath=path.join(evidence,'ideal-study-film.'+(format==='avc'?'mp4':'webm'));await downloaded.saveAs(videoPath);const bytes=await readFile(videoPath);expect(bytes.length).toBeGreaterThan(100000);
  await page.locator('#film-video').evaluate((v:HTMLVideoElement)=>v.play());await page.waitForTimeout(350);expect(await page.locator('#film-video').evaluate((v:HTMLVideoElement)=>v.currentTime)).toBeGreaterThan(.1);await page.getByRole('button',{name:'关闭视频导出',exact:true}).click();
  // Open the downloaded bytes in a new browser page and decode/seek the real file.
  const server=createServer((req,res)=>{if(req.url==='/movie'){const range=/bytes=(\d+)-(\d*)/.exec(req.headers.range||'');const start=range?Number(range[1]):0,end=range&&range[2]?Math.min(Number(range[2]),bytes.length-1):bytes.length-1;res.writeHead(range?206:200,{'Content-Type':format==='avc'?'video/mp4':'video/webm','Accept-Ranges':'bytes','Content-Length':end-start+1,...(range?{'Content-Range':`bytes ${start}-${end}/${bytes.length}`}:{})});res.end(bytes.subarray(start,end+1));}else{res.writeHead(200,{'Content-Type':'text/html'});res.end('<html><body style="margin:0;background:#18231d;display:grid;place-items:center;height:100vh"><video src="/movie" controls muted style="width:100%;max-width:1280px" aria-label="实际导出文件"></video></body></html>');}});
  await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));const address=server.address() as {port:number};const playback=await browser.newPage({viewport:{width:1280,height:800}});
  const frameChecks:any[]=[];
  try{await playback.goto(`http://127.0.0.1:${address.port}/`);await playback.waitForFunction(()=>document.querySelector('video')!.readyState>=2);expect(await playback.locator('video').evaluate((v:HTMLVideoElement)=>v.duration)).toBeCloseTo(10.2,1);
    for(const fraction of [.12,.48,.86]){await page.bringToFront();const box=await page.locator('#film-scrub').boundingBox();await page.mouse.click(box!.x+7+(box!.width-14)*fraction,box!.y+box!.height/2);await settle(page);const t=(await getProject(page)).playhead;const camera=await page.evaluate(()=>(window as any).__film.camera()),sample=await page.evaluate(t=>(window as any).__film.sample(t).camera,t);expect(camera.zoom).toBeCloseTo(sample.zoom,4);for(let i=0;i<3;i++)expect(camera.position[i]).toBeCloseTo(sample.position[i],4);
      // Hidden tabs intentionally suspend scene rendering. Capture each visible surface before switching.
      const previewPixels=await pixels(page,'#film-canvas-host canvas');await playback.bringToFront();await playback.locator('video').evaluate((v:HTMLVideoElement,time:number)=>new Promise<void>(resolve=>{v.onseeked=()=>resolve();v.currentTime=time;}),t);await settle(playback);expect(await playback.locator('video').evaluate((v:HTMLVideoElement)=>v.currentTime)).toBeCloseTo(t,3);const mae=difference(previewPixels,await pixels(playback,'video'));expect(mae).toBeLessThan(9);frameChecks.push({time:t,meanAbsolutePixelDifference:mae,cameraMatchesSampler:true});}
    await shot(playback,'04-downloaded-video-opened.png');await playback.locator('video').evaluate((v:HTMLVideoElement)=>{v.currentTime=0;return v.play();});await playback.waitForFunction(()=>document.querySelector('video')!.ended,{},{timeout:20000});expect(await playback.locator('video').evaluate((v:HTMLVideoElement)=>v.error)).toBeNull();
  }finally{await playback.close();await new Promise<void>(resolve=>server.close(()=>resolve()));}
  expect(errors).toEqual([]);await writeFile(path.join(evidence,'journey.json'),JSON.stringify({timestamp:new Date().toISOString(),browser:browser.version(),projectAfterRestoreExact:true,jsonRoundTripExact:true,format,videoInfo,videoBytes:bytes.length,frameChecks,downloadedFilePlayed:true,errors},null,2));
});

test('镜头时序、排序、撤销重做、连续机位拖动与确定性拖动播放头',async({page})=>{
  await ready(page);await page.locator('#shot-list [data-shot="shot-2"]').click();let before=await getProject(page);
  await change(page,'镜头时长','4.5');expect((await getProject(page)).film.shots[1].duration).toBe(4.5);await page.getByRole('button',{name:'撤销',exact:true}).click();expect((await getProject(page)).film.shots).toEqual(before.film.shots);await page.getByRole('button',{name:'重做',exact:true}).click();expect((await getProject(page)).film.shots[1].duration).toBe(4.5);
  await page.getByRole('button',{name:'前移',exact:true}).click();expect((await getProject(page)).film.shots[0].id).toBe('shot-2');expect((await getProject(page)).selectedShotId).toBe('shot-2');await page.getByRole('button',{name:'撤销',exact:true}).click();expect((await getProject(page)).film.shots[1].id).toBe('shot-2');
  const h=await history(page);await page.getByRole('button',{name:'在画面中调整起点',exact:true}).click();const host=await page.locator('#film-canvas-host').boundingBox();before=await getProject(page);await page.mouse.move(host!.x+host!.width*.55,host!.y+host!.height*.5);await page.mouse.down();await page.mouse.move(host!.x+host!.width*.55+55,host!.y+host!.height*.5+14,{steps:12});await page.mouse.up();expect((await history(page)).past).toBe(h.past+1);expect((await getProject(page)).film.shots[1].start).not.toEqual(before.film.shots[1].start);expect((await getProject(page)).scene).toEqual(before.scene);
  await page.getByRole('button',{name:'撤销',exact:true}).click();expect((await getProject(page)).film.shots[1].start).toEqual(before.film.shots[1].start);
  const scrub=page.getByRole('slider',{name:'播放头'});await scrub.focus();await scrub.press('Home');for(let i=0;i<15;i++)await scrub.press('ArrowRight');await settle(page);const a=await pixels(page,'#film-canvas-host canvas'),t=(await getProject(page)).playhead;await scrub.press('End');await scrub.press('Home');for(let i=0;i<15;i++)await scrub.press('ArrowRight');await settle(page);expect((await getProject(page)).playhead).toBe(t);expect(difference(a,await pixels(page,'#film-canvas-host canvas'))).toBeLessThan(.01);
  await page.getByRole('button',{name:'删除当前镜头'}).click();expect((await getProject(page)).film.shots).toHaveLength(2);await page.locator('#shot-add').click();expect((await getProject(page)).film.shots).toHaveLength(3);await expect(page.locator('#shot-add')).toBeDisabled();
});

test('v1 迁移、非法工程保护、工程内房间编辑及旧存档隔离',async({page})=>{
  const legacy=JSON.parse(await readFile('tests/fixtures/legacy-v1.json','utf8'));await page.addInitScript(plan=>localStorage.setItem('ideal-study.plan.v1',JSON.stringify({plan,savedAt:'legacy'})),legacy);await ready(page);expect((await getProject(page)).scene).toEqual(legacy);const oldStorage=await page.evaluate(()=>localStorage.getItem('ideal-study.plan.v1'));
  await page.locator('#film-save').click();const p=await getProject(page),h=await history(page),stored=await page.evaluate(()=>localStorage.getItem('ideal-study.film.v2'));
  const invalid=['bad json',JSON.stringify({...p,version:99}),JSON.stringify({...p,film:{...p.film,shots:[]}}),JSON.stringify({...p,film:{...p.film,shots:p.film.shots.map((s:any,i:number)=>i===0?{...s,duration:0}:s)}}),JSON.stringify({...p,film:{...p.film,shots:p.film.shots.map((s:any,i:number)=>i===0?{...s,target:[0,99,0]}:s)}}),JSON.stringify({...p,film:{...p.film,shots:p.film.shots.map((s:any,i:number)=>i===0?{...s,start:{...s.start,azimuth:-180}}:s)}})];
  for(const data of invalid){await page.locator('#film-file').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from(data)});await expect(page.locator('#film-toast')).toHaveClass(/error/);expect(await getProject(page)).toEqual(p);expect(await history(page)).toEqual(h);expect(await page.evaluate(()=>localStorage.getItem('ideal-study.film.v2'))).toBe(stored);}
  await page.getByRole('button',{name:'保存并布置房间',exact:true}).click();await expect(page.locator('html')).toHaveAttribute('data-ready','true');await page.getByRole('combobox',{name:'切换当前物件'}).selectOption('desk-1');await page.getByRole('button',{name:'材质：自然橡木',exact:true}).click();await page.getByRole('button',{name:'保存方案',exact:true}).click();await page.getByRole('link',{name:'返回短片工作台'}).click();await expect(page.locator('html')).toHaveAttribute('data-ready','true');expect((await getProject(page)).scene.objects.find((o:any)=>o.id==='desk-1').material).toBe('oak');expect(await page.evaluate(()=>localStorage.getItem('ideal-study.plan.v1'))).toBe(oldStorage);
  await page.locator('#film-file').setInputFiles('tests/fixtures/legacy-v1.json');expect((await getProject(page)).scene).toEqual(legacy);await expect(page.locator('#film-toast')).toContainText('迁移');
});

test('视频取消恢复、无编码降级、低动态和窄屏预览',async({page})=>{
  await page.emulateMedia({reducedMotion:'reduce'});await ready(page);expect((await state(page)).playing).toBe(false);await page.waitForFunction(()=>(window as any).__film.state().encoderReady);const before=await getProject(page);
  await page.locator('#film-export').click();await page.locator('#film-render').click();await expect(page.locator('#film-cancel')).toBeVisible();await page.locator('#film-cancel').click();await expect(page.locator('#export-error')).toContainText('已取消',{timeout:30000});await expect(page.locator('#video-result')).toBeHidden();expect(await getProject(page)).toEqual(before);await page.keyboard.press('Escape');await expect(page.locator('#film-export')).toBeFocused();
  await page.setViewportSize({width:390,height:844});await expect(page.locator('.film-mobile-note')).toBeVisible();await page.locator('#film-play').click();await page.waitForTimeout(180);expect((await state(page)).playing).toBe(true);await page.locator('#film-play').click();await shot(page,'05-film-narrow-390x844.png');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.addInitScript(()=>{Object.defineProperty(window,'VideoEncoder',{value:undefined,configurable:true});});await page.reload();await expect(page.locator('html')).toHaveAttribute('data-ready','true');await page.waitForFunction(()=>(window as any).__film.state().encoderReady);await page.locator('#film-export').click();await expect(page.locator('#film-render')).toBeDisabled();await expect(page.locator('#codec-note')).toContainText('不支持');await page.keyboard.press('Escape');const d=page.waitForEvent('download');await page.locator('#film-json').click();expect((await d).suggestedFilename()).toMatch(/\.json$/);
});

test('无 WebGL 时仍能保存和导出工程，存储失败给出错误',async({page})=>{
  await page.addInitScript(()=>{const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type:string,...args:any[]):any{if(type.includes('webgl'))return null;return original.apply(this,[type,...args] as any);};});await page.goto('./');await expect(page.locator('html')).toHaveAttribute('data-ready','error');await expect(page.locator('#film-loading')).toContainText('暂时无法打开');await expect(page.locator('#film-play')).toBeDisabled();const d=page.waitForEvent('download');await page.locator('#film-json').click();expect((await d).suggestedFilename()).toMatch(/\.json$/);await page.locator('#film-save').click();await expect(page.locator('#film-save-state')).toHaveText('已保存到本地');
  await page.evaluate(()=>{Storage.prototype.setItem=function(){throw new DOMException('Full','QuotaExceededError');};});await page.locator('#film-save').click();await expect(page.locator('#film-toast')).toContainText('本地保存失败');
});

test('默认自动播放、性能测量与浏览器支持的 WebM 格式实际编码回放',async({page,browser})=>{
  test.setTimeout(process.env.CI?780000:240000);const started=Date.now();await page.goto('./');await expect(page.locator('html')).toHaveAttribute('data-ready','true');const loadMs=Date.now()-started;expect((await state(page)).playing).toBe(true);
  const frames:number[]=await page.evaluate(()=>new Promise<number[]>(resolve=>{const samples:number[]=[];let previous=performance.now();const start=previous;function tick(now:number){samples.push(now-previous);previous=now;if(now-start<3000)requestAnimationFrame(tick);else resolve(samples.slice(5));}requestAnimationFrame(tick);}));
  const metrics=await page.evaluate(()=>(window as any).__film.metrics());await page.locator('#film-start').click();await settle(page);const renders=await page.evaluate(()=>(window as any).__film.metrics().renders);await page.waitForTimeout(1000);const idleRenders=await page.evaluate(()=>(window as any).__film.metrics().renders)-renders;expect(idleRenders).toBeLessThanOrEqual(1);
  await page.waitForFunction(()=>(window as any).__film.state().encoderReady);const supported=(await state(page)).formats;const exports:any[]=[];
  for(const format of supported.filter((f:any)=>f.id!=='avc')){await page.locator('#film-export').click();await expect(page.locator('#export-progress-wrap')).toBeHidden();await page.locator('#film-codec').selectOption(format.id);const start=Date.now();await page.locator('#film-render').click();await expect(page.locator('#video-result')).toBeVisible({timeout:process.env.CI?360000:160000});const info=await page.locator('#film-video').evaluate((v:HTMLVideoElement)=>({duration:v.duration,width:v.videoWidth,height:v.videoHeight}));expect(info.duration).toBeCloseTo(10,1);expect([info.width,info.height]).toEqual([1280,720]);const elapsedMs=Date.now()-start;const event=page.waitForEvent('download');await page.locator('#film-download').click();const file=await event;const filePath=path.join(evidence,`default-${format.id}.webm`);await file.saveAs(filePath);await page.locator('#film-video').evaluate((v:HTMLVideoElement)=>new Promise<void>(resolve=>{v.onseeked=()=>resolve();v.currentTime=5;}));expect(await page.locator('#film-video').evaluate((v:HTMLVideoElement)=>v.currentTime)).toBeCloseTo(5,2);await page.locator('#film-video').evaluate((v:HTMLVideoElement)=>v.play());await page.waitForTimeout(350);expect(await page.locator('#film-video').evaluate((v:HTMLVideoElement)=>v.currentTime)).toBeGreaterThan(5.1);exports.push({codec:format.id,...info,elapsedMs,bytes:(await readFile(filePath)).length,replayed:true});await page.locator('#film-close-export').click();}
  const sorted=frames.slice().sort((a,b)=>a-b);await writeFile(path.join(evidence,'performance-and-codecs.json'),JSON.stringify({timestamp:new Date().toISOString(),browser:browser.version(),viewport:page.viewportSize(),loadMs,automaticPlayback:true,rafSamples:frames.length,rafMeanMs:frames.reduce((a,b)=>a+b,0)/frames.length,rafP95Ms:sorted[Math.floor(sorted.length*.95)],idleRendersInOneSecond:idleRenders,metrics,supportedFormats:supported.map((f:any)=>f.label),exports},null,2));
});
