import {test,expect,type Page} from '@playwright/test';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import path from 'node:path';
import {unzipSync} from 'fflate';
const evidence=path.resolve('test-results/projects-evidence');
const plan=(page:Page)=>page.evaluate(()=>(window as any).__study.getPlan());
const current=(page:Page)=>page.evaluate(()=>(window as any).__film?.getProject()??(window as any).__portfolio?.getProject());
async function ready(page:Page){await expect(page.locator('html')).toHaveAttribute('data-ready','true');}
async function go(page:Page,route='projects'){await page.goto('./?workspace='+route);await ready(page);}
async function stored(page:Page,store='projects'):Promise<any[]>{return page.evaluate(store=>new Promise<any[]>((resolve,reject)=>{const open=indexedDB.open('ideal-study.projects',1);open.onerror=()=>reject(open.error);open.onsuccess=()=>{const db=open.result,r=db.transaction(store).objectStore(store).getAll();r.onsuccess=()=>{resolve(r.result);db.close();};r.onerror=()=>reject(r.error);};}),store);}
const record=async(p:Page,id:string)=>(await stored(p)).find(r=>r.id===id);
async function create(page:Page,name:string){await page.locator('#project-new').click();await page.locator('#new-project-name').fill(name);await page.getByRole('button',{name:'创建并布置',exact:true}).click();await page.waitForURL(/workspace=room&id=/);await ready(page);return new URL(page.url()).searchParams.get('id')!;}
async function library(page:Page){await page.locator('#project-library').click();await page.locator('#projects-open').click();await page.waitForURL(/workspace=projects/);await ready(page);}
async function saveRoom(page:Page){await page.locator('#save').click();await expect(page.locator('#toast')).toContainText('已保存到工程库');}
async function bind(page:Page,title:string){await page.locator('#object-picker').selectOption('wall-art');await page.locator('#configure-work').click();await page.locator('#work-name').fill(title);await page.locator('#work-url').fill('https://github.com/yydshly/0905_codexgpt6_project');await page.locator('#apply-work').click();}
async function profile(page:Page,name:string){await page.locator('#portfolio-publish').click();await page.locator('#site-name').fill(name);await page.locator('#site-apply').click();await expect(page.locator('#portfolio-owner')).toHaveText(name);}
async function zip(page:Page,name:string){await page.locator('#portfolio-publish').click();const event=page.waitForEvent('download');await page.locator('#site-download').click();const filename=path.join(evidence,name+'.zip');await(await event).saveAs(filename);await page.keyboard.press('Escape');return JSON.parse(new TextDecoder().decode(unzipSync(await readFile(filename))['project.json']));}
const card=(page:Page,id:string)=>page.locator(`[data-project="${id}"]`);
test.beforeAll(async()=>mkdir(evidence,{recursive:true}));
test.beforeEach(async({page})=>{page.on('dialog',d=>d.accept());});

test('旧房间与短片分别迁入、内容不变、重开去重、后续快速存档保留为新工程',async({page})=>{
  const room=JSON.parse(await readFile('docs/portfolio-evidence/portfolio-room.json','utf8')),film=JSON.parse(await readFile('docs/film-evidence/verified-film-project.json','utf8'));
  const raw={room:JSON.stringify({plan:room,savedAt:'2026-09-04T01:00:00Z'}),film:JSON.stringify({project:film,savedAt:'2026-09-04T02:00:00Z'})};
  await page.addInitScript(raw=>{if(!sessionStorage.getItem('seeded')){localStorage.setItem('ideal-study.plan.v3',raw.room);localStorage.setItem('ideal-study.film.v4',raw.film);sessionStorage.setItem('seeded','true');}},raw);
  await go(page);await expect(page.locator('.project-card')).toHaveCount(2);let rows=await stored(page);expect(rows.map(r=>r.project.scene.objects)).toEqual(expect.arrayContaining([room.objects,[...film.scene.objects,{id:'wall-art',kind:'wallPhoto',x:.6,y:1.93,z:-2.17,rotation:0,material:'oak',width:1.15,height:.82}]]));
  expect(await page.evaluate(()=>[localStorage.getItem('ideal-study.plan.v3'),localStorage.getItem('ideal-study.film.v4')])).toEqual([raw.room,raw.film]);const ids=rows.map(r=>r.id).sort();await page.reload();await ready(page);expect((await stored(page)).map(r=>r.id).sort()).toEqual(ids);
  await page.getByRole('link',{name:'打开快速工作区 ↗'}).click();await ready(page);await page.locator('#plan-name').fill('快速工作区的后续灵感');await page.locator('#plan-name').press('Tab');await library(page);await expect(page.locator('.project-card')).toHaveCount(3);rows=await stored(page);expect(ids.every(id=>rows.some(r=>r.id===id))).toBe(true);await page.reload();await ready(page);await expect(page.locator('.project-card')).toHaveCount(3);
  await writeFile(path.join(evidence,'migration.json'),JSON.stringify({originalBytesPreserved:true,twoSeparateImports:true,reopenDeduplicated:true,laterQuickSaveCreatesNewProject:true,ids},null,2));
});

test('多工程完整闭环：新建、另存为、复制、跨视图、保存版本恢复与分别发布',async({page,browser})=>{
  test.setTimeout(process.env.CI?900000:240000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await go(page);await expect(page.locator('.projects-empty')).toBeVisible();
  const a=await create(page,'林间 · 创作与日常');await bind(page,'A 的摄影作品');await page.locator('#object-picker').selectOption('desk-1');await page.locator('[data-material="walnut"]').click();await saveRoom(page);const aRoom=(await record(page,a)).project.scene;
  await page.locator('#workspace-film').click();await ready(page);expect(new URL(page.url()).searchParams.get('id')).toBe(a);expect((await current(page)).scene.portfolio).toEqual(aRoom.portfolio);await page.locator('#shot-list [data-shot="shot-2"]').click();await page.locator('#shot-duration').fill('4.4');await page.locator('#shot-duration').press('Tab');await page.locator('#film-save').click();await expect(page.locator('#film-save-state')).toHaveText('已保存到本地');
  await page.locator('#workspace-portfolio').click();await ready(page);await profile(page,'林间的作品主页');const aPublished=await zip(page,'project-a-site'),aSaved=await record(page,a);expect(aPublished.scene.portfolio.projects[0].title).toBe('A 的摄影作品');expect(aPublished.film.shots[1].duration).toBe(4.4);
  await page.locator('#project-library').click();await page.locator('#project-copy-name').fill('夜航 · 灵感实验室');await page.locator('#project-save-as').click();await page.waitForURL(url=>url.searchParams.get('id')!==a);await ready(page);const b=new URL(page.url()).searchParams.get('id')!;expect((await record(page,a)).project).toEqual(aSaved.project);
  await page.locator('#portfolio-edit').click();await ready(page);await bind(page,'B 的独立产品');await page.locator('[data-mood="night"]').click();await page.locator('#object-picker').selectOption('desk-1');await page.locator('[data-material="oak"]').click();await page.locator('#workspace-film').click();await ready(page);await page.locator('#shot-list [data-shot="shot-2"]').click();await page.locator('#shot-duration').fill('2.8');await page.locator('#shot-duration').press('Tab');await page.locator('#workspace-portfolio').click();await ready(page);await profile(page,'夜航的实验作品');const bPublished=await zip(page,'project-b-site');expect(bPublished.scene.mood).toBe('night');expect(bPublished.scene.portfolio.projects[0].title).toBe('B 的独立产品');expect(bPublished.film.shots[1].duration).toBe(2.8);expect((await record(page,a)).project).toEqual(aSaved.project);
  await library(page);const c=await create(page,'留白 · 下一份未完成');await library(page);await card(page,a).getByRole('button',{name:'复制工程',exact:true}).click();await page.locator('#new-project-name').fill('林间 · 备选方向');await page.getByRole('button',{name:'创建副本',exact:true}).click();await expect(page.locator('.project-card')).toHaveCount(4);await expect(page.locator('.project-card-preview img')).toHaveCount(4);const copied=(await stored(page)).find(r=>![a,b,c].includes(r.id));expect(copied.revision).toBe(1);expect(copied.project.scene.portfolio).toEqual(aSaved.project.scene.portfolio);
  await page.screenshot({path:path.join(evidence,'01-library-1440x900.png')});await page.locator('#project-search').fill('未完成');await expect(page.locator('.project-card')).toHaveCount(1);await page.locator('#project-search').fill('');
  await card(page,a).getByRole('button',{name:'保存版本',exact:true}).click();await expect(page.locator('.project-version-row')).toHaveCount(aSaved.revision);await page.locator('[data-restore="1"]').click();await page.setViewportSize({width:1280,height:800});await page.screenshot({path:path.join(evidence,'02-history-restore-1280x800.png')});await page.locator('#confirm-restore').click();await expect(page.locator('#projects-message')).toContainText('恢复前的版本仍保留');const restored=await record(page,a);expect(restored.revision).toBe(aSaved.revision+1);expect(restored.project.scene.portfolio.projects).toHaveLength(0);expect((await stored(page,'versions')).filter(v=>v.projectId===a)).toHaveLength(restored.revision);
  await page.reload();await ready(page);await card(page,a).getByRole('link',{name:'继续布置 ↗'}).click();await ready(page);expect((await plan(page)).portfolio.projects).toHaveLength(0);await page.locator('#object-picker').selectOption('taskLamp-1');await page.screenshot({path:path.join(evidence,'03-editor-1280x800.png')});const menu=await page.locator('#project-library').boundingBox();expect(menu!.x+menu!.width).toBeLessThanOrEqual(1280);const del=await page.locator('#delete-item').boundingBox();expect(del!.y+del!.height).toBeLessThanOrEqual(769);
  await library(page);await card(page,a).getByRole('button',{name:'保存版本',exact:true}).click();await page.locator(`[data-restore="${aSaved.revision}"]`).click();await page.locator('#confirm-restore').click();await expect(page.locator('#projects-message')).toContainText('已恢复');expect((await record(page,a)).project).toEqual(aSaved.project);expect((await record(page,b)).project.scene.portfolio.presentation.name).toBe('夜航的实验作品');
  const event=page.waitForEvent('download');await card(page,a).getByRole('button',{name:'备份 JSON ↓'}).click();const json=path.join(evidence,'project-a.json');await(await event).saveAs(json);expect(JSON.parse(await readFile(json,'utf8'))).toEqual(aSaved.project);await page.locator('#projects-file').setInputFiles(json);await expect(page.locator('.project-card')).toHaveCount(5);
  await page.setViewportSize({width:390,height:844});await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:path.join(evidence,'04-library-mobile-390x844.png')});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);await page.setViewportSize({width:1440,height:900});await card(page,b).getByRole('link',{name:'作品展示',exact:true}).click();await ready(page);await page.locator('[data-work]').first().click();await expect(page.locator('#work-title')).toHaveText('B 的独立产品');await page.screenshot({path:path.join(evidence,'05-project-b-visitor-preview.png')});
  expect(errors).toEqual([]);await writeFile(path.join(evidence,'journey.json'),JSON.stringify({timestamp:new Date().toISOString(),browser:browser.version(),ids:{a,b,c,copy:copied.id},aOriginalRevision:aSaved.revision,finalProjectCount:5,distinctPublishedProjects:true,oldVersionsRetained:true,restoredProjectExact:true,otherProjectsUnchanged:true,jsonRoundTripExact:true,errors},null,2));
});

test('并发保存冲突保留两边修改、失败后可另存为，未改动保存不增加版本',async({page,context})=>{
  test.setTimeout(process.env.CI?360000:90000);await go(page);const id=await create(page,'并发保护');await saveRoom(page);const baseline=await record(page,id);await saveRoom(page);expect((await record(page,id)).revision).toBe(baseline.revision);
  const second=await context.newPage();second.on('dialog',d=>d.accept());await second.goto(page.url());await ready(second);await page.locator('[data-mood="night"]').click();await saveRoom(page);const firstSaved=await record(page,id);
  await second.locator('[data-mood="dusk"]').click();await second.locator('#save').click();await expect(second.locator('#toast')).toContainText('另一个页面更新');expect((await record(page,id)).project).toEqual(firstSaved.project);expect((await plan(second)).mood).toBe('dusk');
  await second.locator('#project-library').click();await second.locator('#project-copy-name').fill('保留第二页的黄昏');await second.locator('#project-save-as').click();await second.waitForURL(url=>url.searchParams.get('id')!==id);await ready(second);expect((await plan(second)).mood).toBe('dusk');expect((await stored(second))).toHaveLength(2);await second.close();
});

test('无效导入、数据库不可用、真实事务回滚和键盘焦点',async({page,browser})=>{
  test.setTimeout(process.env.CI?360000:90000);await go(page);await page.locator('#project-new').focus();await page.keyboard.press('Enter');await expect(page.locator('#new-project-name')).toBeFocused();const initialFocus=await page.locator('#new-project-name').evaluate(el=>getComputedStyle(el).outlineStyle);expect(initialFocus).not.toBe('none');await page.keyboard.press('Escape');await expect(page.locator('#project-new')).toBeFocused();
  const id=await create(page,'事务保护');await library(page);const before=await stored(page);await page.locator('#projects-file').setInputFiles({name:'broken.json',mimeType:'application/json',buffer:Buffer.from('{not json')});await expect(page.locator('#projects-message')).toContainText('导入失败');expect(await stored(page)).toEqual(before);
  await card(page,id).getByRole('link',{name:'继续布置 ↗'}).click();await ready(page);const saved=await record(page,id);await page.locator('[data-mood="night"]').click();
  // Abort the real versions write; projects + snapshots must both roll back.
  await page.evaluate(()=>{const add=IDBObjectStore.prototype.add;(window as any).restoreDatabaseWrite=()=>IDBObjectStore.prototype.add=add;IDBObjectStore.prototype.add=function(...args:Parameters<typeof add>){const request=add.apply(this,args);if(this.name==='versions')this.transaction.abort();return request;};});
  await page.locator('#save').click();await expect(page.locator('#toast')).toContainText('本地保存失败');expect((await record(page,id)).project).toEqual(saved.project);expect((await record(page,id)).revision).toBe(saved.revision);expect((await plan(page)).mood).toBe('night');await page.evaluate(()=>(window as any).restoreDatabaseWrite());await saveRoom(page);expect((await record(page,id)).project.scene.mood).toBe('night');
  const unsupported=await browser.newContext();await unsupported.addInitScript(()=>{indexedDB.open=()=>{throw new DOMException('Database disabled','SecurityError');};});const p=await unsupported.newPage();await p.goto(new URL('./?workspace=projects',page.url()).href);await expect(p.locator('html')).toHaveAttribute('data-ready','error');await expect(p.locator('#projects-message')).toContainText('工程库无法读取');await expect(p.getByRole('link',{name:'打开快速工作区 ↗'})).toBeVisible();await expect(p.locator('#project-new')).toBeDisabled();await unsupported.close();
});

test('缩略图不可用时仍能管理工程、配额错误回滚与工程库加载测量',async({page,browser})=>{
  test.setTimeout(process.env.CI?360000:90000);await go(page);const id=await create(page,'预览与存储检查');await library(page);await expect(page.locator('.project-card-preview img')).toBeVisible();const started=Date.now();await page.reload();await ready(page);const readyMs=Date.now()-started;await expect(page.locator('.project-card-preview img')).toBeVisible();const thumbnailReadyMs=Date.now()-started;
  await card(page,id).getByRole('link',{name:'继续布置 ↗'}).click();await ready(page);const before=await record(page,id);await page.locator('[data-mood="night"]').click();
  await page.evaluate(()=>{const add=IDBObjectStore.prototype.add,descriptor=Object.getOwnPropertyDescriptor(IDBTransaction.prototype,'error')!,quota=new WeakSet<IDBTransaction>();Object.defineProperty(IDBTransaction.prototype,'error',{...descriptor,get(){return quota.has(this)?new DOMException('Injected quota failure','QuotaExceededError'):descriptor.get!.call(this);}});IDBObjectStore.prototype.add=function(...args:Parameters<typeof add>){const r=add.apply(this,args);if(this.name==='versions'){quota.add(this.transaction);this.transaction.abort();}return r;};});
  await page.locator('#save').click();await expect(page.locator('#toast')).toContainText('浏览器空间不足');expect((await record(page,id)).project).toEqual(before.project);expect((await record(page,id)).revision).toBe(before.revision);
  const fallback=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce'});await fallback.addInitScript(()=>{const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type:string,...args:any[]){return type.includes('webgl')?null:(original as any).call(this,type,...args);} as any;});const p=await fallback.newPage();await p.goto(new URL('./?workspace=projects',page.url()).href);await ready(p);await p.locator('#projects-file').setInputFiles('docs/projects-evidence/project-a.json');await expect(p.locator('.project-card-preview small')).toHaveText('预览暂不可用 · 工程仍可打开');await expect(p.locator('.project-card')).toHaveCount(1);await p.locator('.project-card').getByRole('button',{name:'复制工程'}).click();await p.locator('#new-project-name').fill('没有显卡也能保留的副本');await p.getByRole('button',{name:'创建副本',exact:true}).click();await expect(p.locator('.project-card')).toHaveCount(2);await expect(p.locator('.project-card-preview small').first()).toContainText('预览暂不可用');await p.locator('#project-search').fill('没有显卡');await expect(p.locator('.project-card')).toHaveCount(1);expect(await p.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);await fallback.close();
  await writeFile(path.join(evidence,'capability-performance.json'),JSON.stringify({timestamp:new Date().toISOString(),browser:browser.version(),cachedOneProjectReadyMs:readyMs,cachedThumbnailReadyMs:thumbnailReadyMs,quotaErrorInjectedWithRealTransactionAbort:true,beforeSnapshotPreserved:true,noWebGLImportCopySearch:true,reducedMotion:true,viewport:{width:390,height:844}},null,2));
});

test('删除工程：取消、备份、全部版本清理、其他工程完整与空状态',async({page,browser})=>{
  test.setTimeout(process.env.CI?360000:90000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await go(page);
  const id=await create(page,'待整理的书房');await page.locator('[data-mood="night"]').click();await saveRoom(page);await library(page);
  await card(page,id).getByRole('button',{name:'复制工程',exact:true}).click();await page.locator('#new-project-name').fill('保留的书房');await page.getByRole('button',{name:'创建副本',exact:true}).click();await expect(page.locator('.project-card')).toHaveCount(2);await expect(page.locator('.project-card-preview img')).toHaveCount(2);
  const before=await stored(page),versions=await stored(page,'versions'),other=before.find(r=>r.id!==id);await page.screenshot({path:path.join(evidence,'07-delete-entry-1440x900.png')});
  await card(page,id).getByRole('button',{name:'删除工程',exact:true}).focus();await page.keyboard.press('Enter');await expect(page.locator('#project-delete-cancel')).toBeFocused();await expect(page.locator('#project-delete-note')).toContainText(`${versions.filter(v=>v.projectId===id).length} 个保存版本`);await page.keyboard.press('Escape');await expect(card(page,id).getByRole('button',{name:'删除工程',exact:true})).toBeFocused();expect(await stored(page)).toEqual(before);
  await card(page,id).getByRole('button',{name:'删除工程',exact:true}).click();await page.locator('#project-delete-cancel').click();expect(await stored(page,'versions')).toEqual(versions);
  await card(page,id).getByRole('button',{name:'删除工程',exact:true}).click();await page.setViewportSize({width:1280,height:800});await page.screenshot({path:path.join(evidence,'08-delete-confirm-1280x800.png')});
  const event=page.waitForEvent('download');await page.locator('#project-delete-backup').click();const json=path.join(evidence,'deleted-project-backup.json');await(await event).saveAs(json);expect(JSON.parse(await readFile(json,'utf8'))).toEqual(before.find(r=>r.id===id).project);
  await page.locator('#project-delete-confirm').click();await expect(page.locator('#projects-message')).toContainText('已删除');await expect(card(page,id)).toHaveCount(0);expect(await stored(page)).toEqual([other]);expect(await stored(page,'versions')).toEqual(versions.filter(v=>v.projectId!==id));await expect(page.locator('#project-new')).toBeFocused();
  await page.reload();await ready(page);await expect(page.locator('.project-card')).toHaveCount(1);await page.setViewportSize({width:390,height:844});await card(page,other.id).getByRole('button',{name:'删除工程',exact:true}).click();await page.screenshot({path:path.join(evidence,'09-delete-mobile-390x844.png')});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);const box=await page.locator('#project-delete-confirm').boundingBox();expect(box!.y+box!.height).toBeLessThanOrEqual(844);await page.locator('#project-delete-confirm').click();await expect(page.locator('.projects-empty')).toBeVisible();expect(await stored(page,'versions')).toEqual([]);await page.reload();await ready(page);await expect(page.locator('.projects-empty')).toBeVisible();expect(errors).toEqual([]);
  await writeFile(path.join(evidence,'deletion.json'),JSON.stringify({timestamp:new Date().toISOString(),browser:browser.version(),cancelAndEscapePreserveData:true,backupExact:true,allVersionsDeleted:true,otherProjectUnchanged:true,refreshEmpty:true,viewports:['1440x900','1280x800','390x844'],errors},null,2));
});

test('删除失败回滚、并发更新保护、被删工程旧标签页仍可另存为',async({page,context})=>{
  test.setTimeout(process.env.CI?360000:90000);await go(page);const id=await create(page,'删除保护');await library(page);await expect(page.locator('.project-card-preview img')).toBeVisible();
  const before=await stored(page),versions=await stored(page,'versions');await page.evaluate(()=>{const del=IDBCursor.prototype.delete;(window as any).restoreDelete=()=>IDBCursor.prototype.delete=del;IDBCursor.prototype.delete=function(){const r=del.call(this);this.source instanceof IDBIndex&&this.source.objectStore.transaction.abort();return r;};});
  await card(page,id).getByRole('button',{name:'删除工程',exact:true}).click();await page.locator('#project-delete-confirm').click();await expect(page.locator('.project-delete-dialog .project-feedback')).toContainText('删除未完成');expect(await stored(page)).toEqual(before);expect(await stored(page,'versions')).toEqual(versions);await page.evaluate(()=>(window as any).restoreDelete());await page.locator('#project-delete-cancel').click();
  const second=await context.newPage();second.on('dialog',d=>d.accept());await second.goto(new URL('./?workspace=room&id='+id,page.url()).href);await ready(second);
  await card(page,id).getByRole('button',{name:'删除工程',exact:true}).click();await second.locator('[data-mood="dusk"]').click();await saveRoom(second);const updated=await record(second,id);await page.locator('#project-delete-confirm').click();await expect(page.locator('.project-delete-dialog .project-feedback')).toContainText('另一个页面更新');expect((await record(page,id)).project).toEqual(updated.project);await page.locator('#project-delete-cancel').click();
  await card(page,id).getByRole('button',{name:'删除工程',exact:true}).click();await expect(page.locator('#project-delete-note')).toContainText(`当前版本 ${updated.revision}`);await page.locator('#project-delete-confirm').click();await expect(page.locator('.projects-empty')).toBeVisible();await second.locator('[data-mood="night"]').click();await second.locator('#save').click();await expect(second.locator('#toast')).toContainText('已被删除');expect(await stored(second)).toEqual([]);expect((await plan(second)).mood).toBe('night');await second.locator('#project-library').click();await second.locator('#project-copy-name').fill('保留旧标签页的灵感');await second.locator('#project-save-as').click();await second.waitForURL(url=>url.searchParams.get('id')!==id);await ready(second);expect((await stored(second))).toHaveLength(1);expect((await plan(second)).mood).toBe('night');await second.close();
});

test('删除迁入工程后刷新不复活原存档，快速存档原始字节保留',async({page})=>{
  const film=JSON.parse(await readFile('docs/projects-evidence/project-a.json','utf8')),raw=JSON.stringify({project:film,savedAt:'2026-09-05T00:00:00Z'});await page.addInitScript(raw=>{localStorage.setItem('ideal-study.film.v4',raw);},raw);await go(page);await expect(page.locator('.project-card')).toHaveCount(1);const id=(await stored(page))[0].id,meta=await stored(page,'meta');await card(page,id).getByRole('button',{name:'删除工程',exact:true}).click();await page.locator('#project-delete-confirm').click();await expect(page.locator('.projects-empty')).toBeVisible();await page.reload();await ready(page);await expect(page.locator('.projects-empty')).toBeVisible();expect(await stored(page,'meta')).toEqual(meta);expect(await page.evaluate(()=>localStorage.getItem('ideal-study.film.v4'))).toBe(raw);
});

test('不保存返回：三个工作页面、放弃与取消、存档版本不变、保存失败可离开',async({page,browser})=>{
  test.setTimeout(process.env.CI?360000:120000);const errors:string[]=[],nativeDialogs:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>nativeDialogs.push(d.type()));await go(page);const id=await create(page,'自由切换的工程');await library(page);await expect(page.locator('.project-card-preview img')).toBeVisible();const original=await stored(page),versions=await stored(page,'versions');
  for(const workspace of ['room','film','portfolio']){
    await page.goto(new URL('./?workspace='+workspace+'&id='+id,page.url()).href);await ready(page);await page.locator('#project-library').click();await expect(page.locator('#project-leave-note')).toContainText('没有未保存修改');await page.locator('#projects-open-unsaved').click();await page.waitForURL(/workspace=projects/);await ready(page);expect(await stored(page)).toEqual(original);expect(await stored(page,'versions')).toEqual(versions);
  }
  await card(page,id).getByRole('link',{name:'继续布置 ↗'}).click();await ready(page);await page.locator('[data-mood="night"]').click();await page.locator('#project-library').click();await page.screenshot({path:path.join(evidence,'10-return-choices-1440x900.png')});await page.locator('#projects-open-unsaved').click();await expect(page.locator('#project-leave-cancel')).toBeFocused();await page.setViewportSize({width:1280,height:800});await page.screenshot({path:path.join(evidence,'11-discard-confirm-1280x800.png')});await page.locator('#project-leave-cancel').click();await expect(page.locator('#projects-open-unsaved')).toBeFocused();await page.keyboard.press('Escape');expect((await plan(page)).mood).toBe('night');await page.locator('#project-library').click();await page.locator('#projects-open-unsaved').click();await page.locator('#project-leave-discard').click();await page.waitForURL(/workspace=projects/);await ready(page);expect(await stored(page)).toEqual(original);expect(await stored(page,'versions')).toEqual(versions);
  await card(page,id).getByRole('link',{name:'镜头短片',exact:true}).click();await ready(page);await page.locator('#shot-list [data-shot="shot-2"]').click();await page.locator('#shot-duration').fill('4.9');await page.locator('#shot-duration').press('Tab');await page.locator('#project-library').click();await page.locator('#projects-open-unsaved').click();await page.locator('#project-leave-discard').click();await page.waitForURL(/workspace=projects/);await ready(page);expect(await stored(page)).toEqual(original);
  await card(page,id).getByRole('link',{name:'作品展示',exact:true}).click();await ready(page);await page.locator('#portfolio-file').setInputFiles('docs/projects-evidence/project-a.json');await expect(page.locator('#portfolio-owner')).not.toHaveText('');await expect.poll(async()=>await page.evaluate(()=>(window as any).__portfolio.getProject().name)).toBe('林间 · 创作与日常');await page.locator('#project-library').click();await page.locator('#projects-open-unsaved').click();await expect(page.locator('#project-leave-confirm')).toBeVisible();await page.locator('#project-leave-discard').click();await page.waitForURL(/workspace=projects/);await ready(page);expect(await stored(page)).toEqual(original);expect(await stored(page,'versions')).toEqual(versions);
  await card(page,id).getByRole('link',{name:'继续布置 ↗'}).click();await ready(page);expect((await plan(page)).mood).toBe('day');await page.locator('[data-mood="dusk"]').click();await page.evaluate(()=>{const add=IDBObjectStore.prototype.add;IDBObjectStore.prototype.add=function(...args:Parameters<typeof add>){const r=add.apply(this,args);if(this.name==='versions')this.transaction.abort();return r;};});await page.locator('#project-library').click();await page.locator('#projects-open').click();await expect(page.locator('.project-manager-dialog .project-feedback')).toContainText('保存未完成');await page.locator('#projects-open-unsaved').click();await page.locator('#project-leave-discard').click();await page.waitForURL(/workspace=projects/);await ready(page);expect(await stored(page)).toEqual(original);expect(await stored(page,'versions')).toEqual(versions);expect(nativeDialogs).toEqual([]);expect(errors).toEqual([]);
  const quick=await browser.newContext(),quickPage=await quick.newPage();await quickPage.goto(new URL('./?workspace=room',page.url()).href);await ready(quickPage);await quickPage.locator('#save').click();await expect(quickPage.locator('#toast')).toContainText('当前浏览器');const raw=await quickPage.evaluate(()=>localStorage.getItem('ideal-study.plan.v3'));await quickPage.locator('[data-mood="night"]').click();await quickPage.locator('#project-library').click();await quickPage.locator('#projects-open-unsaved').click();await quickPage.locator('#project-leave-discard').click();await quickPage.waitForURL(/workspace=projects/);await ready(quickPage);expect(await quickPage.evaluate(()=>localStorage.getItem('ideal-study.plan.v3'))).toBe(raw);expect((await stored(quickPage))[0].project.scene.mood).toBe('day');await quick.close();
  await writeFile(path.join(evidence,'leave-without-saving.json'),JSON.stringify({timestamp:new Date().toISOString(),browser:browser.version(),cleanReturn:['room','film','portfolio'],discard:['room','film','portfolio import','quick room'],cancelPreservesEditing:true,savedRecordsAndVersionsUnchanged:true,quickStorageBytesPreserved:true,saveFailureCanLeave:true,nativeDialogs,errors},null,2));
});
