import {test,expect,type Page} from '@playwright/test';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import {createServer,type Server} from 'node:http';
import path from 'node:path';
import {unzipSync} from 'fflate';

const evidence=path.resolve('test-results/publish-evidence'),site=path.resolve('test-results/publish-site');
let server:Server,siteURL:string;
const state=(p:Page)=>p.evaluate(()=>(window as any).__study.getPlan());
async function ready(p:Page,workspace='room'){await p.goto('./?workspace='+workspace);await expect(p.locator('html')).toHaveAttribute('data-ready','true');}
async function bind(p:Page,id:string,title:string,part?:string){await p.locator('#object-picker').selectOption(id);if(part)await p.locator('#binding-part').selectOption(part);await p.locator('#configure-work').click();await p.locator('#work-choice').selectOption('');await p.locator('#work-name').fill(title);await p.locator('#work-description').fill('这是我的创作项目，欢迎探索和体验。');await p.locator('#work-url').fill('https://github.com/yydshly/0905_codexgpt6_project');await p.locator('#apply-work').click();await expect(p.locator('.portfolio-config')).toHaveCount(0);}
async function meshClick(p:Page,target:string,title:string){const marker=p.locator(`[data-target="${target}"]`);await expect(marker).toBeVisible();const b=await marker.boundingBox();await p.locator('#portfolio-markers').click();await p.mouse.click(b!.x+b!.width/2,b!.y+b!.height/2);await expect(p.locator('#work-title')).toHaveText(title);await p.keyboard.press('Escape');await p.locator('#portfolio-markers').click();}
test.beforeAll(async()=>{await mkdir(evidence,{recursive:true});await mkdir(site,{recursive:true});server=createServer(async(req,res)=>{try{const name=decodeURIComponent(new URL(req.url!,'http://local').pathname).replace(/^\/my-portfolio/,'').replace(/^\//,'')||'index.html',file=path.resolve(site,name);if(!file.startsWith(site+path.sep))throw Error();const bytes=await readFile(file);res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.json')?'application/json':'text/html');res.end(bytes);}catch{res.statusCode=404;res.end('Not found');}});await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));siteURL='http://127.0.0.1:'+(server.address() as any).port;});
test.afterAll(async()=>{await new Promise<void>(r=>server.close(()=>r()));});

test('全部 11 类物件整体关联、双部位优先级、历史和旧配置迁移',async({page})=>{
  test.setTimeout(process.env.CI?600000:180000);await ready(page);
  const kinds=['desk','chair','monitor','shelf','taskLamp','floorLamp','plant','rug','sofa','bed','wallPhoto'];const checked=[];
  for(const kind of kinds){let item=(await state(page)).objects.find((o:any)=>o.kind===kind);if(!item){await page.locator(`[data-add="${kind}"]`).click();item=(await state(page)).objects.find((o:any)=>o.kind===kind);}
    await bind(page,item.id,'作品 · '+kind,['desk','monitor'].includes(kind)?'object':undefined);
    expect((await state(page)).portfolio.bindings.some((b:any)=>b.target.itemId===item.id&&b.target.partId==='object')).toBe(true);checked.push(kind);
  }
  await bind(page,'desk-1','桌面书籍的专属项目','book-1');await bind(page,'monitor-1','屏幕的专属项目','screen');const saved=await state(page);
  await page.locator('#object-picker').selectOption('wall-art');await page.locator('#delete-item').click();expect((await state(page)).portfolio.bindings).toHaveLength(saved.portfolio.bindings.length-1);await page.locator('#undo').click();expect((await state(page)).portfolio).toEqual(saved.portfolio);await page.locator('#redo').click();await page.locator('#undo').click();
  await page.locator('#save').click();await page.reload();await expect(page.locator('html')).toHaveAttribute('data-ready','true');expect((await state(page)).portfolio).toEqual(saved.portfolio);
  await page.locator('#file-input').setInputFiles('docs/portfolio-evidence/portfolio-room.json');await expect(page.locator('#toast')).toContainText('已导入');const old=JSON.parse(await readFile('docs/portfolio-evidence/portfolio-room.json','utf8'));expect((await state(page)).portfolio.version).toBe(2);expect((await state(page)).portfolio.bindings).toEqual(old.portfolio.bindings);expect((await state(page)).objects).toEqual(old.objects);
  await writeFile(path.join(evidence,'catalog.json'),JSON.stringify({timestamp:new Date().toISOString(),wholeObjectKinds:checked,bindingsBeforeMigration:saved.portfolio.bindings.length,historyAndRefresh:true,v1PortfolioMigrated:true},null,2));
});

test('个人主页闭环：物件绑定、设置保存、ZIP、独立访客与 GLB 宿主',async({page,browser})=>{
  test.setTimeout(process.env.CI?600000:180000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await ready(page);
  await bind(page,'wall-art','墙上的摄影集');await bind(page,'desk-1','我的工具产品','object');await bind(page,'desk-1','创作笔记','book-1');await bind(page,'shelf-1','开源作品集');
  await bind(page,'chair-1','不应发布的草稿');await page.locator('#configure-work').click();await page.locator('#unlink-work').click();
  await page.locator('#object-picker').selectOption('wall-art');await page.locator('#configure-work').click();await page.screenshot({path:path.join(evidence,'01-all-object-author-1440x900.png')});await page.keyboard.press('Escape');
  await page.locator('#export').click();let download=page.waitForEvent('download');await page.locator('#export-glb').click();const glb=path.join(evidence,'personal-room.glb');await(await download).saveAs(glb);await page.keyboard.press('Escape');
  await page.locator('#workspace-portfolio').click();await expect(page.locator('html')).toHaveAttribute('data-ready','true');
  await meshClick(page,'wall-art/object','墙上的摄影集');await meshClick(page,'desk-1/book-1','创作笔记');await meshClick(page,'desk-1/object','我的工具产品');
  await page.locator('#portfolio-publish').click();await page.locator('#site-name').fill('林间 · 创作者');await page.locator('#site-headline').fill('把想法，\n做成可以体验的作品。');await page.locator('#site-bio').fill('设计、代码与生活。\n欢迎来到我的创作空间。');await page.locator('#site-apply').click();await page.reload();await expect(page.locator('html')).toHaveAttribute('data-ready','true');await expect(page.locator('#portfolio-owner')).toHaveText('林间 · 创作者');
  await page.locator('#portfolio-publish').click();await page.screenshot({path:path.join(evidence,'02-publish-1440x900.png')});
  await page.route('**/site-kit/manifest.json',r=>r.fulfill({status:503,body:'unavailable'}));await page.locator('#site-download').click();await expect(page.locator('.config-error')).toContainText('打包失败');await page.unroute('**/site-kit/manifest.json');
  download=page.waitForEvent('download');await page.locator('#site-download').click();const zipPath=path.join(evidence,'personal-homepage.zip');await(await download).saveAs(zipPath);await expect(page.locator('.config-error')).toContainText('部署后才会获得公开网址');await page.keyboard.press('Escape');
  const archive=unzipSync(await readFile(zipPath));for(const [name,bytes]of Object.entries(archive)){const filename=path.resolve(site,name);expect(filename.startsWith(site+path.sep)).toBe(true);await mkdir(path.dirname(filename),{recursive:true});await writeFile(filename,bytes);}
  const published=JSON.parse(new TextDecoder().decode(archive['project.json']));await writeFile(path.join(evidence,'published-project.json'),archive['project.json']);expect(published.scene.portfolio.bindings).toHaveLength(4);expect(published.scene.portfolio.projects).toHaveLength(4);expect(published.scene.portfolio.projects.some((w:any)=>w.title==='不应发布的草稿')).toBe(false);
  const context=await browser.newContext({viewport:{width:1440,height:900}});await context.addInitScript(()=>{Storage.prototype.getItem=()=>{throw Error('Visitor must not use author storage');};});const visitor=await context.newPage();const requests:string[]=[];visitor.on('request',r=>requests.push(r.url()));visitor.on('pageerror',e=>errors.push(e.message));const start=Date.now();await visitor.goto(siteURL+'/my-portfolio/');await expect(visitor.locator('html')).toHaveAttribute('data-ready','true');const loadMs=Date.now()-start;
  expect(await visitor.evaluate(()=>(window as any).__portfolio.getProject())).toEqual(published);const desktopMetrics=await visitor.evaluate(()=>(window as any).__portfolio.metrics());await expect(visitor.locator('#portfolio-edit')).toHaveCount(0);await expect(visitor.locator('#portfolio-publish')).toHaveCount(0);await expect(visitor.locator('#portfolio-import')).toHaveCount(0);
  await visitor.screenshot({path:path.join(evidence,'03-visitor-1440x900.png')});await meshClick(visitor,'wall-art/object','墙上的摄影集');await meshClick(visitor,'desk-1/book-1','创作笔记');
  await visitor.setViewportSize({width:1280,height:800});await visitor.locator('[data-work]').first().click();await visitor.screenshot({path:path.join(evidence,'04-visitor-detail-1280x800.png')});const popup=visitor.waitForEvent('popup');await visitor.locator('.work-visit').click();const target=await popup;await target.waitForURL('https://github.com/yydshly/0905_codexgpt6_project');await target.close();await visitor.keyboard.press('Escape');
  await visitor.setViewportSize({width:390,height:844});await visitor.getByRole('button',{name:'深夜氛围'}).click();await visitor.locator('[data-work]').first().click();await visitor.screenshot({path:path.join(evidence,'05-mobile-night-390x844.png')});await expect(visitor.locator('.work-visit')).toBeInViewport();await visitor.keyboard.press('Escape');expect(await visitor.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await visitor.goto(siteURL+'/');await expect(visitor.locator('html')).toHaveAttribute('data-ready','true');expect(await visitor.evaluate(()=>(window as any).__portfolio.getProject())).toEqual(published);expect(requests.every(u=>u.startsWith(siteURL))).toBe(true);const metrics=await visitor.evaluate(()=>(window as any).__portfolio.metrics());await context.close();
  await ready(page,'viewer');await page.locator('#glb-file').setInputFiles(glb);await expect(page.locator('html')).toHaveAttribute('data-loaded','true');await page.locator('#glb-project').setInputFiles(path.join(evidence,'published-project.json'));await expect(page.locator('#glb-work-status')).toContainText('已关联 4');await page.locator('[data-target="wall-art/object"]').click();await expect(page.locator('#work-title')).toHaveText('墙上的摄影集');await page.keyboard.press('Escape');
  await ready(page,'integration');await page.locator('#host-project').setInputFiles(path.join(evidence,'published-project.json'));await page.frameLocator('#study-frame').locator('[data-target="wall-art/object"]').click();await expect(page.locator('#work-title')).toHaveText('墙上的摄影集');expect(errors).toEqual([]);
  await writeFile(path.join(evidence,'journey.json'),JSON.stringify({timestamp:new Date().toISOString(),browser:browser.version(),siteURL,zipBytes:(await readFile(zipPath)).length,files:Object.keys(archive),loadMs,desktopMetrics,metrics,visitorNoAuthorStorage:true,projectExact:true,wholeAndPartActualMeshClicked:true,independentGLB:true,iframe:true,allRuntimeRequestsLocal:true,downloadFailureRecovered:true,errors},null,2));
});

test('访客缺失文件、无 WebGL、减少动态及键盘降级',async({page,browser})=>{
  // Self-contained site fixture using actual built distribution and an old exported project.
  const old=JSON.parse(await readFile('docs/portfolio-evidence/portfolio-room.json','utf8'));
  await mkdir(path.join(site,'assets'),{recursive:true});for(const name of ['index.html','assets/site.js','assets/site.css'])await writeFile(path.join(site,name),await readFile(path.join('public/site-kit',name)));
  await writeFile(path.join(site,'project.json'),JSON.stringify(old));await page.route('**/project.json',r=>r.fulfill({status:404,body:'missing'}));await page.goto(siteURL+'/');await expect(page.locator('html')).toHaveAttribute('data-ready','error');await expect(page.getByRole('alert')).toContainText('加载失败');await page.unroute('**/project.json');
  const context=await browser.newContext({reducedMotion:'reduce',viewport:{width:390,height:844}});await context.addInitScript(()=>{const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(this:HTMLCanvasElement,type:string,...args:any[]){return type.startsWith('webgl')?null:original.call(this,type as any,...args);} as any;});const fallback=await context.newPage();await fallback.goto(siteURL+'/');await expect(fallback.locator('html')).toHaveAttribute('data-ready','true');await expect(fallback.locator('#portfolio-status')).toContainText('3D 暂不可用');const card=fallback.locator('[data-work]').first();await card.focus();await fallback.keyboard.press('Enter');await expect(fallback.locator('.work-close')).toBeFocused();await expect(fallback.locator('.work-visit')).toBeVisible();await fallback.keyboard.press('Escape');await expect(card).toBeFocused();await context.close();
});

test('每类物件真实几何均可点击，整体入口不依赖模型部位',async({page})=>{
  test.setTimeout(process.env.CI?600000:180000);await ready(page);await page.locator('[data-add="sofa"]').click();await page.locator('[data-add="bed"]').click();const seed=await state(page);await ready(page,'portfolio');const clicked=[];
  for(const original of seed.objects){const item={...original,x:0,z:original.kind==='wallPhoto'?-2.17:0},parent=item.parentId?{...seed.objects.find((o:any)=>o.id===item.parentId),x:0,z:0}:null;
    const fixture={...seed,selectedId:null,objects:parent?[parent,item]:[item],portfolio:{...seed.portfolio,projects:[{id:'one',title:'点击 '+item.kind,description:'逐类验证',tags:'',url:'https://github.com/yydshly/0905_codexgpt6_project'}],bindings:[{target:{itemId:item.id,partId:'object'},projectId:'one',action:'openProject'}]}};
    await page.locator('#portfolio-file').setInputFiles({name:'single-object.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(fixture))});await expect(page.locator('#portfolio-status')).toContainText('已载入');await meshClick(page,item.id+'/object','点击 '+item.kind);clicked.push(item.kind);
  }
  expect(new Set(clicked).size).toBe(11);await writeFile(path.join(evidence,'actual-geometry.json'),JSON.stringify({timestamp:new Date().toISOString(),actualMeshKinds:clicked,domMarkersHiddenDuringClick:true,fixture:'One isolated catalog object in real room, including required desk parent for desktop objects'},null,2));
});
