import { createFilmProject, parseFilmProject } from './film-model';
import { initialPlan, MAX_JSON_BYTES } from './model';
import { createProject, getProject, listProjects, listVersions, migrateLegacyProjects, projectURL, restoreVersion, setProjectThumbnail, type ProjectRecord } from './project-store';
import { renderMissingThumbnails } from './project-thumbnail';
import { preparePhotos } from './photos';
import './projects.css';

document.body.className='projects-app';document.title='我的工程 · 理想书房';
const $=<T extends HTMLElement=HTMLElement>(s:string)=>document.querySelector<T>(s)!;
$('#app').innerHTML=`<main class="projects-page"><header class="projects-header"><div class="projects-brand"><span>◇</span>理想书房 <small>/ 我的工程</small></div><a class="project-action quiet" href="?workspace=room">打开快速工作区 ↗</a></header><div class="projects-main"><section class="projects-heading"><div><span class="project-overline">A COLLECTION OF YOUR OWN</span><h1>灵感不止一间。</h1><p>每一套房间、每一段镜头、每一个作品主页。<br/>分别保存，随时回来继续。</p></div><aside class="projects-local"><strong>在这台设备，安心创作。</strong><p>工程与保存版本仅存于当前浏览器。<br/>重要作品请导出 JSON，带走一份备份。</p></aside></section><section class="projects-toolbar" aria-label="工程库操作"><button id="project-new" class="project-action primary">＋ 新建工程</button><button id="project-import" class="project-action">导入 JSON 为新工程</button><label class="projects-search">查找工程<input type="search" id="project-search" placeholder="输入工程名称" /></label></section><p id="projects-count" class="projects-count"></p><p id="projects-message" class="projects-message" role="status" aria-live="polite">正在读取你的工程…</p><section id="projects-grid" class="projects-grid" aria-label="已保存工程"></section><footer class="projects-footer"><span>房间 · 镜头短片 · 作品展示，同一套工程随处继续。</span><span id="projects-storage">本地工程库 · 保存版本持续保留</span></footer></div><input id="projects-file" type="file" accept=".json,application/json" hidden /></main>`;
let records:ProjectRecord[]=[],thumbnailTask=0;
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]!));
const when=(s:string)=>new Intl.DateTimeFormat('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date(s));
function report(message:string,error=false){$('#projects-message').textContent=message;$('#projects-message').classList.toggle('error',error);}
function download(record:ProjectRecord){const url=URL.createObjectURL(new Blob([JSON.stringify(record.project,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=record.project.name.replace(/[\\/:*?"<>|]/g,'-')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),15000);report('当前工程 JSON 已交给浏览器下载；保存版本仍保留在工程库。');}
function render(){
  const query=$<HTMLInputElement>('#project-search').value.trim().toLocaleLowerCase(),shown=records.filter(r=>r.project.name.toLocaleLowerCase().includes(query));$('#projects-count').textContent=`${records.length} 套工程${query?` · 找到 ${shown.length} 套`:''} / 按最近保存排序`;
  $('#projects-grid').innerHTML=shown.length?shown.map(record=>`<article class="project-card" data-project="${esc(record.id)}"><div class="project-card-preview">${record.thumbnail?`<img src="${esc(record.thumbnail)}" alt="${esc(record.project.name)}的实际房间预览" loading="lazy"/>`:'<small>预览生成中…</small>'}<span>版本 ${record.revision}</span></div><div class="project-card-content"><h2 title="${esc(record.project.name)}">${esc(record.project.name)}</h2><div class="project-card-meta"><span>${when(record.updatedAt)}</span><span>${record.project.scene.objects.length} 件物品</span><span>${record.project.scene.portfolio.projects.length} 个作品</span></div><div class="project-card-links"><a class="project-action primary" href="${projectURL('room',record.id)}">继续布置 ↗</a><a class="project-action" href="${projectURL('film',record.id)}">镜头短片</a><a class="project-action" href="${projectURL('portfolio',record.id)}">作品展示</a></div><div class="project-card-footer"><button data-action="history">保存版本</button><button data-action="copy">复制工程</button><button data-action="export">备份 JSON ↓</button></div></div></article>`).join(''):`<div class="projects-empty"><span class="project-overline">${query?'KEEP EXPLORING':'MAKE ROOM FOR IDEAS'}</span><h2>${query?'没有找到这套工程':'为下一份灵感，留一间房。'}</h2><p>${query?'换个名字搜索，或清空搜索查看所有工程。':'新建一套布置完整的书房，也可以导入以前的 JSON 方案。'}</p></div>`;
}
async function reload(){records=await listProjects();render();const task=++thumbnailTask;void renderMissingThumbnails(records.filter(r=>!r.thumbnail),async(record,url)=>{await setProjectThumbnail(record.id,record.revision,url);if(task!==thumbnailTask)return;const current=records.find(r=>r.id===record.id);if(current?.revision===record.revision){current.thumbnail=url;const card=[...document.querySelectorAll<HTMLElement>('.project-card')].find(c=>c.dataset.project===record.id),preview=card?.querySelector('.project-card-preview');if(preview){preview.querySelector('small')?.remove();const image=document.createElement('img');image.src=url;image.alt=record.project.name+'的实际房间预览';preview.prepend(image);}}}).catch(()=>{document.querySelectorAll('.project-card-preview small').forEach(el=>el.textContent='预览暂不可用 · 工程仍可打开');});}
function nameDialog(original?:ProjectRecord){
  const dialog=document.createElement('dialog');dialog.className='project-manager-dialog';dialog.setAttribute('aria-labelledby','project-name-title');dialog.innerHTML=`<form><span class="project-overline">A NEW BEGINNING</span><h2 id="project-name-title">${original?'给灵感，另一个方向。':'从这一间，开始。'}</h2><p class="project-dialog-note">${original?'复制完整房间、镜头和作品配置。原工程与它的保存版本保持完整。':'从已布置好的书房开始。房间、镜头和作品主页，都属于这套新工程。'}</p><label>工程名称<input id="new-project-name" maxlength="48" required /></label><p class="project-feedback" role="status"></p><button class="project-action primary" type="submit">${original?'创建副本':'创建并布置'}</button><button class="project-action quiet" type="button" data-close>返回工程库</button></form>`;dialog.querySelector<HTMLInputElement>('input')!.value=original?(original.project.name.slice(0,43)+' · 副本'):'新的创作书房';
  let busy=false;dialog.querySelector('[data-close]')!.addEventListener('click',()=>dialog.close());dialog.addEventListener('cancel',e=>{if(busy)e.preventDefault();});const focus=document.activeElement as HTMLElement;dialog.addEventListener('close',()=>{dialog.remove();focus?.focus();});
  dialog.querySelector('form')!.onsubmit=async e=>{e.preventDefault();if(busy)return;const name=dialog.querySelector<HTMLInputElement>('input')!.value.trim();if(!name){dialog.querySelector('.project-feedback')!.textContent='请填写工程名称。';return;}busy=true;dialog.querySelectorAll<HTMLButtonElement>('button').forEach(b=>b.disabled=true);try{const p=original?structuredClone(original.project):createFilmProject(initialPlan());p.name=name;p.scene.name=name;const record=await createProject(p,original?.thumbnail,original?'复制工程':'创建工程');if(original){dialog.close();await reload();report('副本已创建，原工程保持完整。');}else location.href=projectURL('room',record.id);}catch(error){dialog.querySelector('.project-feedback')!.textContent=(error as Error).message;}finally{busy=false;dialog.querySelectorAll<HTMLButtonElement>('button').forEach(b=>b.disabled=false);}};
  document.body.append(dialog);dialog.showModal();dialog.querySelector('input')!.select();
}
async function historyDialog(id:string){
  const focus=document.activeElement as HTMLElement,dialog=document.createElement('dialog');dialog.className='project-manager-dialog project-versions-dialog';dialog.setAttribute('aria-labelledby','versions-title');dialog.innerHTML='<span class="project-overline">SAVED MOMENTS</span><h2 id="versions-title">保存版本</h2><p class="project-dialog-note" id="versions-note"></p><div class="project-version-list"></div><div class="project-restore-confirm" hidden></div><p class="project-feedback" role="status"></p><button type="button" class="project-action quiet" data-close>返回工程库</button>';document.body.append(dialog);dialog.showModal();let busy=false;
  dialog.querySelector('[data-close]')!.addEventListener('click',()=>dialog.close());dialog.addEventListener('cancel',e=>{if(busy)e.preventDefault();});dialog.addEventListener('close',()=>{dialog.remove();focus?.focus();});
  try{const record=await getProject(id),versions=await listVersions(id);dialog.querySelector('#versions-note')!.textContent=record.project.name+' · 每次有修改的保存会留下一个版本；恢复时会追加新版本，当前版本仍可找回。';dialog.querySelector('.project-version-list')!.innerHTML=versions.map(v=>`<article class="project-version-row"><div><strong>版本 ${v.revision} · ${esc(v.label)}</strong><small>${when(v.savedAt)} · ${v.project.scene.objects.length} 件物品 · ${v.project.scene.portfolio.projects.length} 个作品</small></div><button type="button" class="project-action" data-restore="${v.revision}" ${v.revision===record.revision?'disabled':''}>${v.revision===record.revision?'当前版本':'恢复此版本'}</button></article>`).join('');
    dialog.querySelectorAll<HTMLButtonElement>('[data-restore]').forEach(button=>button.onclick=()=>{if(busy)return;const revision=Number(button.dataset.restore),confirm=dialog.querySelector<HTMLElement>('.project-restore-confirm')!;confirm.hidden=false;confirm.innerHTML=`<p>将版本 ${revision} 恢复为新的版本 ${record.revision+1}。现在的版本 ${record.revision} 会继续保留，可随时恢复。</p><button class="project-action primary" id="confirm-restore">确认恢复</button><button class="project-action" id="cancel-restore">取消</button>`;confirm.querySelector('#cancel-restore')!.addEventListener('click',()=>{confirm.hidden=true;button.focus();});confirm.querySelector<HTMLButtonElement>('#confirm-restore')!.onclick=async()=>{if(busy)return;busy=true;dialog.querySelectorAll<HTMLButtonElement>('button').forEach(b=>b.disabled=true);try{const restored=await restoreVersion(id,record.revision,revision);dialog.close();await reload();report(`已恢复为版本 ${restored.revision}，恢复前的版本仍保留。`);}catch(error){dialog.querySelector('.project-feedback')!.textContent=(error as Error).message;}finally{busy=false;dialog.querySelectorAll<HTMLButtonElement>('button').forEach(b=>b.disabled=false);}};confirm.querySelector<HTMLButtonElement>('#confirm-restore')!.focus();confirm.scrollIntoView({block:'nearest'});});
  }catch(error){dialog.querySelector('.project-feedback')!.textContent=(error as Error).message;}
}
$('#project-new').onclick=()=>nameDialog();$('#project-search').oninput=render;$('#project-import').onclick=()=>$<HTMLInputElement>('#projects-file').click();
$('#projects-grid').onclick=async e=>{const button=(e.target as HTMLElement).closest<HTMLButtonElement>('[data-action]'),id=button?.closest<HTMLElement>('[data-project]')?.dataset.project;if(!id||!button)return;try{const record=await getProject(id);if(button.dataset.action==='copy')nameDialog(record);else if(button.dataset.action==='history')await historyDialog(id);else download(record);}catch(error){report((error as Error).message,true);}};
$<HTMLInputElement>('#projects-file').onchange=async e=>{const input=e.target as HTMLInputElement,file=input.files?.[0];input.value='';if(!file)return;try{if(file.size>MAX_JSON_BYTES)throw new Error('请选择 6 MB 以内的 JSON 工程。');const raw=JSON.parse(await file.text()),p=parseFilmProject(raw).project;if(raw.app==='ideal-study')p.name=p.scene.name;await preparePhotos(p.scene);await createProject(p,undefined,'导入 JSON');await reload();report('已导入为独立的新工程，已有工程没有更改。');}catch(error){report('导入失败：'+(error as Error).message,true);}};
try{const notes=await migrateLegacyProjects();await reload();report(notes.join(' ')||'保存过的工程都在这里。未完成的灵感，也可以随时继续。');document.documentElement.dataset.ready='true';const id=new URLSearchParams(location.search).get('history');if(id)await historyDialog(id);void navigator.storage?.estimate().then(e=>{if(e.usage!==undefined)$('#projects-storage').textContent=`当前站点已用 ${(e.usage/1048576).toFixed(1)} MB · 版本持续保留`;}).catch(()=>{});}catch(error){report('工程库无法读取：'+(error as Error).message+' 原始存档保留，可返回快速工作区导出 JSON。',true);$('#project-new').setAttribute('disabled','');$('#project-import').setAttribute('disabled','');document.documentElement.dataset.ready='error';}
