import type { FilmProject } from './film-model';
import { parsePresentation, boundWorks } from './portfolio-model';
import { createSitePackage } from './site-export';

export function openPublishDialog(project:FilmProject,apply:(next:FilmProject)=>Promise<void>,persistent:boolean){
  const dialog=document.createElement('dialog');dialog.className='portfolio-config publish-config';dialog.setAttribute('aria-labelledby','publish-title');
  dialog.innerHTML=`<form><span class="work-eyebrow">YOUR ROOM, YOUR WEBSITE</span><h2 id="publish-title">把这个房间，变成你的主页。</h2><p class="config-note">配置个人介绍，下载独立网站。访客打开后即可探索房间、点击作品。</p><label>展示名称<input id="site-name" required maxlength="30" /></label><label>页面标题<textarea id="site-headline" required maxlength="60" rows="2"></textarea></label><label>个人简介<textarea id="site-bio" maxlength="160" rows="2"></textarea></label><div class="publish-summary"></div><p class="config-note" id="publish-save-note"></p><details class="publish-help"><summary>如何部署到 GitHub Pages？</summary><ol><li>下载 ZIP，解压后得到 index.html、assets 和 project.json。</li><li>把这些文件放入你自己的静态网站仓库。</li><li>在 Settings → Pages 选择对应分支与根目录，或用已有 Pages Actions 发布。</li></ol><p>网站包支持仓库子路径，也可部署到其他静态服务器。更新作品后，重新下载并部署。</p><a href="https://docs.github.com/en/pages/getting-started-with-github-pages/creating-a-github-pages-site" target="_blank" rel="noopener noreferrer">GitHub 官方部署说明 ↗</a></details><p class="config-error" role="status" aria-live="polite"></p><div class="config-actions"><button type="button" id="publish-close">返回</button><button type="submit" id="site-apply"></button><button type="button" id="site-download">下载网站 ZIP</button></div></form>`;
  const $=<T extends HTMLElement=HTMLElement>(s:string)=>dialog.querySelector<T>(s)!;const profile=project.scene.portfolio.presentation;
  $<HTMLInputElement>('#site-name').value=profile.name;$<HTMLTextAreaElement>('#site-headline').value=profile.headline;$<HTMLTextAreaElement>('#site-bio').value=profile.bio;
  $('.publish-summary').textContent=`${project.scene.objects.length} 件物品 · ${project.scene.portfolio.bindings.length} 个入口 · ${boundWorks(project.scene.portfolio).length} 个作品`;
  const contents=document.createElement('p');contents.className='config-note';contents.textContent='发布包包含房间、照片和已关联作品，部署后公开可见；未关联的作品草稿不会打包。';$('.publish-summary').after(contents);
  $('#site-apply').textContent=persistent?'保存设置并预览':'应用并预览';$('#publish-save-note').textContent=persistent?'保存设置会更新当前浏览器中的对应工程；网站发布需要下载后部署。':'示例或导入内容仅更新本次预览；可导出工程保留设置。';
  function next(){const p=structuredClone(project);p.scene.portfolio.presentation=parsePresentation({name:$<HTMLInputElement>('#site-name').value,headline:$<HTMLTextAreaElement>('#site-headline').value,bio:$<HTMLTextAreaElement>('#site-bio').value});return p;}
  let busy=false;function setBusy(value:boolean){busy=value;dialog.querySelectorAll<HTMLButtonElement>('button').forEach(b=>b.disabled=value);}
  dialog.querySelector('form')!.onsubmit=async e=>{e.preventDefault();if(busy)return;try{setBusy(true);await apply(next());dialog.close();}catch(error){$('.config-error').textContent='设置未保存：'+(error as Error).message;}finally{setBusy(false);}};
  $('#site-download').onclick=async()=>{if(busy||!dialog.querySelector('form')!.reportValidity())return;setBusy(true);$('.config-error').textContent='正在打包房间、作品与网页运行文件…';try{const blob=await createSitePackage(next()),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='我的作品主页.zip';a.click();setTimeout(()=>URL.revokeObjectURL(url),15000);$('.config-error').textContent=`网站包已交给浏览器下载（${(blob.size/1024/1024).toFixed(2)} MB）。部署后才会获得公开网址。`;}catch(error){$('.config-error').textContent='打包失败：'+(error as Error).message;}finally{setBusy(false);}};
  $('#publish-close').onclick=()=>dialog.close();dialog.addEventListener('cancel',e=>{if(busy)e.preventDefault();});dialog.addEventListener('close',()=>{dialog.remove();document.querySelector<HTMLElement>('#portfolio-publish')?.focus();},{once:true});document.body.append(dialog);dialog.showModal();
}
